---
name: edu
full_name: 18F Edu
description: |
18F Edu is the self-guided training component of the 18F Learn initiative. It aims to supplement the 18F Guides with hands-on exercises that can solidify your grasp of those materials. The combined body of 18F Guides and 18F Edu training modules aim to support the concepts promoted in the U.S. Digital Services Playbook.
type: docs
owner_type: project
status: active
stage: alpha
testable: false
licenses:
  edu:
    name: Public Domain (CC0)
    url: https://creativecommons.org/publicdomain/zero/1.0/ 
links:
- url: https://pages.18f.gov/edu/
  text: 18F Edu home page
tasks: https://github.com/18F/edu/issues
team:
- github: mbland
  role: lead
- github: gboone
  role: lead
- github: emileighoutlaw
- github: awfrancisco
- github: kategarklavs
- github: jackiekazil
- github: quepol
