markdown: redcarpet
name: 18F Edu [DRAFT]
exclude:
- go
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

permalink: pretty
highlighter: rouge

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: Accessibility
  url: https://github.com/18F/edu-accessibility/
  internal: false
- text: How to test and measure content
  url: https://pages.18f.gov/edu-measure-content/
  internal: false

repos:
- name: 18F Edu
  description: Main repository
  url: https://github.com/18F/edu
- name: Accessibility
  description: Accessibility training
  url: https://github.com/18F/edu-accessibility/
- name: How to test and measure content
  description: Measure content training
  url: https://github.com/18F/edu-measure-content

# Style Variables
brand_color: "#1188ff"

google_analytics_ua: UA-48605964-19

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"
